apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-service
  namespace: microservices
  labels:
    app: mongo-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-service
  template:
    metadata:
      labels:
        app: mongo-service
    spec:
      containers:
        - name: mongo-service
          image: mongo:latest
          imagePullPolicy: Never # ใช้ image จาก local
          ports:
            - containerPort: 27017
