apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: microservices
  labels:
    app: mongo-service
spec:
  type: NodePort # ใช้ NodePort สำหรับ local development
  selector:
    app: mongo-service
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 32017
