# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: microservices-config
#   namespace: microservices
# data:
#   # API Gateway Configuration
#   PORT: '3000'

#   test: 'hello world na'
#   t: 't'

#   # User Service Configuration
#   USER_SERVICE_HOST: 'user-service'
#   USER_SERVICE_PORT: '3001'

#   # Product Service Configuration
#   PRODUCT_SERVICE_HOST: 'product-service'
#   PRODUCT_SERVICE_PORT: '3002'

#   # Order Service Configuration
#   ORDER_SERVICE_HOST: 'order-service'
#   ORDER_SERVICE_PORT: '3003'

#   # Notification Service Configuration (ยังเก็บไว้สำหรับ backward compatibility)
#   NOTIFICATION_SERVICE_HOST: 'notification-service'
#   NOTIFICATION_SERVICE_PORT: '3004'

#   # RabbitMQ Configuration
#   RABBITMQ_URL: 'amqp://admin:password@rabbitmq:5672'

#   # MongoDB Configuration
#   MONGODB_URI: 'mongodb://mongo-service/nest'

#   # Common Configuration
#   HOST: '0.0.0.0'

apiVersion: v1
kind: ConfigMap
metadata:
  name: microservices-config
  namespace: microservices
data:
{{- range $key, $value := .Values.apiGateway.env }}
  {{ $key }}: {{ $value | quote }}
{{- end }}