{{- if .Values.apiGateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: {{ .Values.namespace }}
  labels:
    app: api-gateway
spec:
  type: {{ .Values.apiGateway.service.type }} # ใช้ NodePort สำหรับ local development
  selector:
    app: api-gateway
  ports:
    - port: {{ .Values.apiGateway.service.port }}
      targetPort: {{ .Values.apiGateway.containerPort }}
      nodePort: {{ .Values.apiGateway.service.nodePort }}
{{- end }}