apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: microservices
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: api-gateway:latest
          imagePullPolicy: Never # ใช้ image จาก local
          ports:
            - containerPort: 3000
          # จะใช้ envFrom เพื่อดึง environment variables ทั้งหมดจาก ConfigMap
          envFrom:
            - configMapRef:
                name: microservices-config
            - secretRef:
                name: microservices-secret
          # ถ้าอยากกำหนด env ทีละตัวแทนการใช้ envFrom ให้ใช้โค้ดด้านล่างนี้แทน
          # env:
          #   - name: PORT
          #     valueFrom:
          #       configMapKeyRef:
          #         name: microservices-config
          #         key: PORT
          #   - name: USER_SERVICE_HOST
          #     valueFrom:
          #       configMapKeyRef:
          #         name: microservices-config
          #         key: USER_SERVICE_HOST
          #   - name: USER_SERVICE_PORT
          #     valueFrom:
          #       configMapKeyRef:
          #         name: microservices-config
          #         key: USER_SERVICE_PORT
          #   - name: PRODUCT_SERVICE_HOST
          #     valueFrom:
          #       configMapKeyRef:
          #         name: microservices-config
          #         key: PRODUCT_SERVICE_HOST
          #   - name: PRODUCT_SERVICE_PORT
          #     valueFrom:
          #       configMapKeyRef:
          #         name: microservices-config
          #         key: PRODUCT_SERVICE_PORT
          #   - name: ORDER_SERVICE_HOST
          #     valueFrom:
          #       configMapKeyRef:
          #         name: microservices-config
          #         key: ORDER_SERVICE_HOST
          #   - name: ORDER_SERVICE_PORT
          #     valueFrom:
          #       configMapKeyRef:
          #         name: microservices-config
          #         key: ORDER_SERVICE_PORT
          #   - name: NOTIFICATION_SERVICE_HOST
          #     valueFrom:
          #       configMapKeyRef:
          #         name: microservices-config
          #         key: NOTIFICATION_SERVICE_HOST
          #   - name: NOTIFICATION_SERVICE_PORT
          #     valueFrom:
          #       configMapKeyRef:
          #         name: microservices-config
          #         key: NOTIFICATION_SERVICE_PORT
          #   - name: RABBITMQ_URL
          #     valueFrom:
          #       configMapKeyRef:
          #         name: microservices-config
          #         key: RABBITMQ_URL
          #   # - name: MONGODB_URI
          #   #   valueFrom:
          #   #     configMapKeyRef:
          #   #       name: microservices-config
          #   #       key: MONGODB_URI
          #   - name: MONGODB_URI
          #     value: 'mongodb://mongo-service/nest'
          resources:
            requests:
              memory: '128Mi'
              cpu: '100m'
            limits:
              memory: '256Mi'
              cpu: '200m'
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
          volumeMounts:
            - name: app-volume
              mountPath: /app/mount1/mount2 # โฟลเดอร์ใน pod
            - name: app-volume2
              mountPath: /app/mount3 # โฟลเดอร์ใน pod
      volumes:
        - name: app-volume
          hostPath:
            path: /Users/weeraphatyian/Desktop/k8s/mount # โฟลเดอร์บนโฮสต์
            type: Directory # จะไม่สร้างโฟลเดอร์ใหม่ถ้าไม่มี และจะ error
        - name: app-volume2
          hostPath:
            path: /Users/weeraphatyian/Desktop/k8s/mount2 # โฟลเดอร์บนโฮสต์
            type: DirectoryOrCreate # จะสร้างโฟลเดอร์ใหม่ถ้าไม่มี
