apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: microservices
  labels:
    app: api-gateway
spec:
  type: NodePort # ใช้ NodePort สำหรับ local development
  selector:
    app: api-gateway
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000

# # for use ingress change NodePort to ClusterIP
# apiVersion: v1
# kind: Service
# metadata:
#   name: api-gateway
#   namespace: microservices
#   labels:
#     app: api-gateway
# spec:
#   type: ClusterIP # ใช้ ClusterIP เพื่อให้ Ingress เข้าถึง
#   selector:
#     app: api-gateway
#   ports:
#     - port: 30000
#       targetPort: 3000
